# Generated by Django 4.2.28 on 2026-02-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talabalar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vazifabajarish',
            options={'ordering': ['vazifa_raqam']},
        ),
    ]
