# Generated by Django 4.2.28 on 2026-02-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guruhlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guruh',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
